### ISSUE TITLE
Support for serde's rename feature

### ISSUE THREAD

**Issue by xifel** [abdolence/struct-path-rs#3]
While using the firestore crate I noticed that the path! macro doesn't support the rename feature of serde.

Example:
```rust
use serde::Serialize;
use struct_path::path;

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct Test {
    test_attribute: String,
}

fn main() {
    let t = Test {
        test_attribute: "Test".to_string(),
    };
    let json = serde_json::to_string(&t).unwrap();
    println!("{}", json);
    let path = path!(Test::test_attribute);
    println!("{}", path);
}
```

Current output:
```
{"testAttribute":"Test"}
test_attribute
```

Expected output:
```
{"testAttribute":"Test"}
testAttribute
```

Is it possible to support this feature?

**Comment by abdolence** [comment]
Hey, 

`struct_path::path` works on any structures and doesn't have any connection with serde. The macro supports case conversion using parameter (e.g. `; case="camel")`).

However, what are you looking for actually exists in firestore itself. I left you an example at:

https://github.com/abdolence/firestore-rs/blob/master/examples/camel-case.rs

And this case `path!`/`path_camel_case!` are macro implemented in `firestore` crate (https://github.com/abdolence/firestore-rs/blob/master/src/struct_path_macro.rs) and rely on the struct-path macro. So, don't import both, you don't need to import low-leveled macro `path!` from struct-path yourself. Just import `firestore::*;`

**Comment by abdolence** [comment]
Would be possible great detecting this automatically without using different macro name or options, but I don't think it is easy to implement without introducing a new proc macro and attributes on your structures.

**Comment by xifel** [comment]
Ah, I have overlooked the `path_camel_case!` macro. Thank you and thank you for the example and for your time.
