### ISSUE TITLE
Optional child

### ISSUE THREAD

**Issue by FredrikNoren** [abdolence/struct-path-rs#4]
Hi, great library!

Is there any way to get this to work?

```rust
struct A {
  b: Option<B>
}
struct B {
  test: String
}
path!(A::b::test);
```

I know I can do `path!(A::b, B::test)`, but would be nice to go directly as well

**Comment by abdolence** [comment]
Hey, I agree it would be less cumbersome to have something like that, but currently, it is not supported, unfortunately. 

It is a bit complicated to identify type `B` to validate the type, and sometimes it has additional types like Option, Vec, Box, etc, so this is possible to some degree, but complicated :)

**Comment by abdolence** [comment]
Ah, now I remember, sorry, for your case it may actually work with:

```
TestStructParent::value_child.child_value_str
```

**Comment by abdolence** [comment]
I'll give a try for some popular cases for `Option`, `Vec`, etc. The syntax though will be probably the same as for other cases:
```
path!(A::b.test)
```

**Comment by abdolence** [comment]
Ok, have an idea of how it can be implemented this with less troubles:
https://github.com/abdolence/struct-path-rs/pull/5

The only downside I need to introduce additional syntax such as 
```
path!(A::b~test)
```
What do you think?

**Comment by FredrikNoren** [comment]
@abdolence Oh nice! I think that looks amazing :)

**Comment by abdolence** [comment]
Then so be it :)
https://github.com/abdolence/struct-path-rs/releases/tag/v0.2.3

**Comment by FredrikNoren** [comment]
Awesome :D Nice work, and thank you!
